### ISSUE TITLE
Efi Fix

### ISSUE THREAD

**Issue by Lorys89** [Naiteiy/Dell-Vostro-5590-Hackintosh-EFI#1]
see my repo https://github.com/Lorys89/DELL_VOSTRO_5490 (compatible for vostro 5590 model)
cfg lock, dvmt and other fix

**Comment by Naiteiy** [comment]
&nbsp; Thank you for your letter. I never expected that a Chinese novice like me could also receive emails from a master on Github. I am very happy. But if it's an automated email, please ignore my words.
&nbsp; I perfected the EFI for Vostro5590 a month ago and upgraded to Ventura Beta6 a few days ago, just like you. I also unlocked the CFG Lock and modified the DVMT options the same way you did. I also fixed the sleep problem and made the perfect USB customization, and the SD card slot worked fine. Except for the microphone and MX250 standalone graphics card, everything else is normal. However, when I was about to upload it to Github, I found that some Chinese websites about Hackintosh reprinted my EFI and sold it to make money, so I was so angry that I didn't upload the EFI file with complete functions.Your tutorial is very detailed and will definitely help people who need it!
&nbsp; Please forgive me for my poor English!

------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Naiteiy/Dell-Vostro-5590-Hackintosh-EFI"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年9月2日(星期五) 下午4:18
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[Naiteiy/Dell-Vostro-5590-Hackintosh-EFI] Efi Fix (Issue #1)





 
see my repo https://github.com/Lorys89/DELL_VOSTRO_5490 (compatible for vostro 5590 model)
 cfg lock, dvmt and other fix

**Comment by Lorys89** [comment]
Thanks for the nice words, it's not an automated email, I wrote you proprThanks for the nice words, it's not an automated email, I wrote you just 🤷.
Did you already know me? If you need ask me as wellDid you already know me? If you need ask me as well 👍.

**Comment by Naiteiy** [comment]
So that's it
I am not familiar with Github yet. I saw your message in my emailbox at first. So I thought it was just an email until I open Github and saw the issue you had closed. Don't laugh at me.
Ha ha ha that's funny
